##.title
## â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“
##
## ðŸ‡½ðŸ‡¾ðŸ‡¿ & Dev
##
## Copyright â’¸ Robert Mollentze, xyzand.dev
##
## Licensing details can be found in the LICENSE file in the root directory.
##
## â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“â–“
##.title~

name: xyz_utils
description: This package provides a set of utilities that are commonly used in Dart apps. It is also the foundation for other packages in the XYZ ecosystem.
repository: https://github.com/robmllze/xyz_utils
version: 0.56.1

## -----------------------------------------------------------------------------

environment:
  sdk: ">= 3.3.1 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  analyzer: ^6.4.1
  collection: ^1.18.0
  equatable: ^2.0.5
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.11.0
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^3.0.0
